name: Pruebas Automatizadas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Buscar y ejecutar pruebas en carpetas -v1
        run: |
          for dir in $(find . -type d -name "*-v1" -maxdepth 1); do
            echo "Ejecutando pruebas en $dir"
            cd $dir
            chmod +x ./mvnw
            ./mvnw -q test
            cd ..
          done
